### ISSUE TITLE
Additional pane actions

### ISSUE THREAD

**Issue by junegunn** [junegunn/heytmux#3]
Currently Heytmux only supports `expect` action. `sleep` or` keys` might also be useful.

```yaml
- servers:
  - server 1:
    - vmstat 2 | tee log
    - sleep: 3
    - keys: c-c
```
