### ISSUE TITLE
Custom layouts

### ISSUE THREAD

**Issue by rpunkfu** [junegunn/heytmux#5]
Hi, is it possible to define custom layouts like in tmuxinator?
https://stackoverflow.com/questions/9812000/specify-pane-percentage-in-tmuxinator-project/9976282#9976282

**Comment by junegunn** [comment]
Heytmux simply passes layout to the argument of `select-layout` command, so it should work.

Confirmed, it does.

```yaml
- test window:
    layout: 34dd,181x45,0,0{90x45,0,0[90x22,0,0,265,90x11,0,23,267,90x10,0,35,268],90x45,91,0,266}
    panes:
      - pane1: echo foo
      - pane2: echo bar
      - pane3:
      - pane4:
```

However, unlike tmuxinator, Heytmux is designed to work with any subset of the panes in the windows, some existing, some non-existing, using standard layout presets seems to make more sense than absolute layout expressions.
